n7ws 3la files .yaml wnbedel

path: /open5gs/install/var/log/open5gs/amf.log
instead of /home/user/open5gs/install/var/log/open5gs/amf.log



docker build -t open5gs-amf-test -f Dockerfile.amf .

docker run -it --entrypoint /bin/bash open5gs-amf-test

apt update 
apt install nano 

n7ws win n7ot hada (amf.yaml) :
"
logger:
  file: /dev/stdout
"

ndir la commande :
/open5gs/bin/open5gs-amfd -c /open5gs/etc/open5gs/amf.yaml
